/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import ALLCLASS.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;


public class AddNewCustomerForm extends javax.swing.JFrame {
    
    private static final String DB_URL = "jdbc:mysql://localhost:3306/art_management";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "manya123";

    /**
     * Creates new form AddNewCustomerForm
     */
    public AddNewCustomerForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerHeader = new javax.swing.JPanel();
        formheader = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        minmizbtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        youridlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        namefiled = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        repasswordlabel = new javax.swing.JLabel();
        rePasswordField = new javax.swing.JPasswordField();
        addresslable = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        setidlabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        CustomerHeader.setBackground(new java.awt.Color(0, 0, 0));

        formheader.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        formheader.setForeground(new java.awt.Color(255, 255, 255));
        formheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formheader.setText("ART GALLERY");

        closebtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        closebtn.setForeground(new java.awt.Color(255, 255, 255));
        closebtn.setText("X");
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });

        minmizbtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minmizbtn.setForeground(new java.awt.Color(255, 255, 255));
        minmizbtn.setText("-");
        minmizbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minmizbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minmizbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CustomerHeaderLayout = new javax.swing.GroupLayout(CustomerHeader);
        CustomerHeader.setLayout(CustomerHeaderLayout);
        CustomerHeaderLayout.setHorizontalGroup(
            CustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerHeaderLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(formheader, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318)
                .addComponent(minmizbtn)
                .addGap(18, 18, 18)
                .addComponent(closebtn)
                .addGap(36, 36, 36))
        );
        CustomerHeaderLayout.setVerticalGroup(
            CustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formheader)
                    .addComponent(minmizbtn)
                    .addComponent(closebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(34, 47, 62));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        youridlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        youridlabel.setForeground(new java.awt.Color(255, 255, 255));
        youridlabel.setText("Gallery id :");
        jPanel1.add(youridlabel);
        youridlabel.setBounds(30, 90, 120, 60);

        namelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("Name :");
        jPanel1.add(namelabel);
        namelabel.setBounds(50, 140, 85, 24);

        namefiled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namefiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namefiledKeyTyped(evt);
            }
        });
        jPanel1.add(namefiled);
        namefiled.setBounds(150, 140, 165, 23);

        passwordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Password :");
        jPanel1.add(passwordlabel);
        passwordlabel.setBounds(20, 180, 110, 24);

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(passwordField);
        passwordField.setBounds(150, 180, 165, 23);

        repasswordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        repasswordlabel.setForeground(new java.awt.Color(255, 255, 255));
        repasswordlabel.setText("RePassword :");
        jPanel1.add(repasswordlabel);
        repasswordlabel.setBounds(10, 220, 124, 24);

        rePasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(rePasswordField);
        rePasswordField.setBounds(150, 220, 165, 23);

        addresslable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addresslable.setForeground(new java.awt.Color(255, 255, 255));
        addresslable.setText("Address :");
        jPanel1.add(addresslable);
        addresslable.setBounds(20, 260, 96, 24);

        addressfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressfieldKeyTyped(evt);
            }
        });
        jPanel1.add(addressfield);
        addressfield.setBounds(150, 260, 163, 23);

        registerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerButton.setText("Submit");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(150, 300, 160, 29);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 200, 60);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 110, 140, 22);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(510, 110, 370, 370);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG-20240423-WA0028.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-170, 0, 1660, 770);

        setidlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setidlabelActionPerformed(evt);
            }
        });
        jPanel2.add(setidlabel);
        setidlabel.setBounds(240, 250, 64, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer no:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 280, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CustomerHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CustomerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Boolean checkname() {
    String name = namefiled.getText();
    String query = "SELECT COUNT(*) FROM artist WHERE aname = ?";
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/art_management", "root", "manya123");
         PreparedStatement statement = connection.prepareStatement(query)) {
        statement.setString(1, name);
        ResultSet resultSet = statement.executeQuery();
        resultSet.next();
        int count = resultSet.getInt(1);
        if(count == 0){
            return true;
        }
        else{
            return false;
        }
         // Returns true if name doesn't exist, false otherwise
    } catch (SQLException e) {
        e.printStackTrace();
        return false; // Handle any potential SQL exception
    }
}

private Boolean checkdata() {
    // Perform local validation checks
    if (namefiled.getText().equals("") || addressfield.getText().equals("") || passwordField.getText().equals("") || rePasswordField.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Empty Fields.", "Message", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    if (!passwordField.getText().equals(rePasswordField.getText())) {
        JOptionPane.showMessageDialog(this, "Passwords don't match.", "Message", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    // Validate name against the database
    if (!checkname()) {
        JOptionPane.showMessageDialog(this, "This name is used before.\nChange it.", "Message", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}

    
    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        LOGINFORM xx = new LOGINFORM();
        xx.setVisible(true);
        xx.pack();
        xx.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void minmizbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmizbtnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minmizbtnMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        if (checkdata()) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String sql = "INSERT INTO customer (gid,name, address, password) VALUES (?, ?, ?, ?)";
            String userCust = "INSERT INTO USERS (username,password,role) VALUES (?,?,?)";
            
            try (PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
                String cGid = jTextField1.getText();
                String cName = namefiled.getText();
                String cAdd = addressfield.getText();
                String cPass = passwordField.getText();
                
                stmt.setString(1,cGid);
                stmt.setString(2,cName );
                stmt.setString(3,cAdd );
                stmt.setString(4, cPass);
                
                String roleC = "customer";
                
                PreparedStatement statementUc = conn.prepareStatement(userCust);
                statementUc.setString(1,cName);
                statementUc.setString(2,cPass);
                statementUc.setString(3,roleC);
                statementUc.executeUpdate();
                
                int rowsAffected = stmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data Saved.", "Message", JOptionPane.INFORMATION_MESSAGE);
                    LOGINFORM xx = new LOGINFORM();
                    xx.setVisible(true);
                    xx.pack();
                    xx.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to save data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void namefiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namefiledKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_namefiledKeyTyped

    private void addressfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressfieldKeyTyped
        // TODO add your handling code here:
         if(Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_addressfieldKeyTyped

    private void setidlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setidlabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setidlabelActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCustomerForm().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerHeader;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel addresslable;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel formheader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel minmizbtn;
    private javax.swing.JTextField namefiled;
    private javax.swing.JLabel namelabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel repasswordlabel;
    private javax.swing.JTextField setidlabel;
    private javax.swing.JLabel youridlabel;
    // End of variables declaration//GEN-END:variables
}
