/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;
import ALLCLASS.*;
import java.awt.Image;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

import javax.swing.table.DefaultTableModel;


public class AdminPage extends javax.swing.JFrame {
     private Connection connection;

    /**
     * Creates new form AdminPage
     */
  
    
    private final JLabel totalSoldPhotosLabel;
    public AdminPage() {
       initComponents();
        connectToDatabase();
        loadDataFromDatabase();
        totalSoldPhotosLabel = new JLabel();
        add(totalSoldPhotosLabel);
        totalSoldPhotosLabel.setBounds(20, 20, 200, 30);
        updateTotalSoldPhotosLabel();
    }
    
     private void updateTotalSoldPhotosLabel() {
        int totalSoldPhotos = calculateTotalSoldPhotos();
        totalSoldPhotosLabel.setText("Total Sold Photos: " + totalSoldPhotos);
    }

    private int calculateTotalSoldPhotos() {
        int totalSoldPhotos = 0;

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/art_management", "root", "manya123")) {
            String query = "SELECT COUNT(*) FROM buys_artwork";
            try (PreparedStatement stmt = conn.prepareStatement(query)) {
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    totalSoldPhotos = rs.getInt(1);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return totalSoldPhotos;
    }
    
    
    private void connectToDatabase() {
        try {
            // Connect to your database
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/art_management", "root", "manya123");
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadDataFromDatabase() {
        // Load data from the database
        set_home_data();
        set_customer_tbl();
        set_artist_tbl();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minminze = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        adminbody = new javax.swing.JTabbedPane();
        hometab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        totalartsitslabel = new javax.swing.JLabel();
        totalartsitslabel1 = new javax.swing.JLabel();
        totalcustomersslabel2 = new javax.swing.JLabel();
        totalcustomersslabel1 = new javax.swing.JLabel();
        totalartworkslabel2 = new javax.swing.JLabel();
        totalartworkslabel3 = new javax.swing.JLabel();
        totalartboughtphtotolabel4 = new javax.swing.JLabel();
        totalartboughtphtotolabel3 = new javax.swing.JLabel();
        totalearnedmoneylabel5 = new javax.swing.JLabel();
        totalearnedmoneylabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datatblstab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artisttbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        customertbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Head.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ART GALLERY");

        minminze.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minminze.setForeground(new java.awt.Color(255, 255, 255));
        minminze.setText("-");
        minminze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minminze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minminzeMouseClicked(evt);
            }
        });

        closeicon.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        closeicon.setForeground(new java.awt.Color(255, 255, 255));
        closeicon.setText("X");
        closeicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373)
                .addComponent(minminze)
                .addGap(18, 18, 18)
                .addComponent(closeicon)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minminze)
                    .addComponent(closeicon)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        adminbody.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        hometab.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        totalartsitslabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartsitslabel.setText("Total Artists :");

        totalartsitslabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalcustomersslabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalcustomersslabel2.setText("Total Customer :");

        totalcustomersslabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalartworkslabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartworkslabel2.setText("Total artworks :");

        totalartworkslabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalartboughtphtotolabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartboughtphtotolabel4.setText("Total Sold Photos :");

        totalartboughtphtotolabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalearnedmoneylabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalearnedmoneylabel5.setText("Total Earned Money :");

        totalearnedmoneylabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("System Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalearnedmoneylabel5)
                        .addGap(27, 27, 27)
                        .addComponent(totalearnedmoneylabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalartboughtphtotolabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalartworkslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalartworkslabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalartboughtphtotolabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalcustomersslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalcustomersslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalartsitslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalartsitslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartsitslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartsitslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalcustomersslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalcustomersslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartworkslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartworkslabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartboughtphtotolabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartboughtphtotolabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalearnedmoneylabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalearnedmoneylabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        hometab.add(jPanel1);
        jPanel1.setBounds(680, 110, 510, 430);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viktor-talashuk-S39X1P9gsfA-unsplash.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        hometab.add(jLabel11);
        jLabel11.setBounds(0, -140, 1440, 740);

        adminbody.addTab("Home", hometab);

        datatblstab.setLayout(null);

        artisttbl.setBackground(new java.awt.Color(0, 0, 0));
        artisttbl.setForeground(new java.awt.Color(255, 255, 255));
        artisttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Age", "Nationality", "n.Style.Arts", "StyleOfArts", "T.Photos", "T.B.photos", "T.E.Money"
            }
        ));
        jScrollPane1.setViewportView(artisttbl);

        datatblstab.add(jScrollPane1);
        jScrollPane1.setBounds(240, 240, 878, 240);

        customertbl.setBackground(new java.awt.Color(0, 0, 0));
        customertbl.setForeground(new java.awt.Color(255, 255, 255));
        customertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Address", "T. B.Photo", "T.M.Spent"
            }
        ));
        jScrollPane2.setViewportView(customertbl);

        datatblstab.add(jScrollPane2);
        jScrollPane2.setBounds(240, 70, 878, 129);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artists :");
        datatblstab.add(jLabel2);
        jLabel2.setBounds(30, 380, 168, 34);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Customers :");
        datatblstab.add(jLabel3);
        jLabel3.setBounds(10, 120, 230, 34);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jon-tyson-QL0FAxaq2z0-unsplash.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setMaximumSize(new java.awt.Dimension(1450, 850));
        datatblstab.add(jLabel13);
        jLabel13.setBounds(0, 0, 1450, 850);

        adminbody.addTab("Data Tbls", datatblstab);

        jLayeredPane1.setLayer(adminbody, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminbody)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminbody, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    
    private void minminzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minminzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minminzeMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        //System.exit(0);
        this.dispose();
        new LOGINFORM().setVisible(true);
    }//GEN-LAST:event_closeiconMouseClicked

   
    
     
    
    
    private void set_home_data()
    {
        try {
            PreparedStatement stmt = connection.prepareStatement("SELECT COUNT(*) FROM artist");
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                totalartsitslabel1.setText(rs.getString(1));
            }
            stmt.close();
            
            stmt = connection.prepareStatement("SELECT COUNT(*) FROM customer");
            rs = stmt.executeQuery();
            if (rs.next()) {
                totalcustomersslabel1.setText(rs.getString(1));
            }
            stmt.close();
            
            stmt = connection.prepareStatement("SELECT COUNT(*) FROM artwork");
            rs = stmt.executeQuery();
            if (rs.next()) {
                totalartworkslabel3.setText(rs.getString(1));
            }
            stmt.close();
            
            stmt = connection.prepareStatement("SELECT COUNT(*) FROM artwork");
            rs = stmt.executeQuery();
            if (rs.next()) {
                totalartboughtphtotolabel3.setText(rs.getString(1));
            }
            stmt.close();
            
            stmt = connection.prepareStatement("SELECT SUM(price) FROM artwork");
            rs = stmt.executeQuery();
            if (rs.next()) {
                totalearnedmoneylabel4.setText(rs.getString(1) + " $");
            }
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void set_artist_tbl()
    {
        try {
            DefaultTableModel tblmodel = (DefaultTableModel) artisttbl.getModel();
            tblmodel.setRowCount(0); // Clear existing rows
            
            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM artist");
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                int artistId = rs.getInt("artistid");
                String artistName = rs.getString("aname");
                int artistAge = rs.getInt("age");
                String artistNationality = rs.getString("nationality");
                
                PreparedStatement stmt2 = connection.prepareStatement("SELECT COUNT(*) FROM artwork WHERE artid = ?");
                stmt2.setInt(1, artistId);
                ResultSet rs2 = stmt2.executeQuery();
                int totalArtwork = 0;
                if (rs2.next()) {
                    totalArtwork = rs2.getInt(1);
                }
                stmt2.close();
                
                stmt2 = connection.prepareStatement("SELECT COUNT(*) FROM artwork WHERE artid = ? ");
                stmt2.setInt(1, artistId);
                rs2 = stmt2.executeQuery();
                int totalBoughtPhotos = 0;
                if (rs2.next()) {
                    totalBoughtPhotos = rs2.getInt(1);
                }
                stmt2.close();
                
                stmt2 = connection.prepareStatement("SELECT SUM(price) FROM artwork WHERE artid = ? ");
                stmt2.setInt(1, artistId);
                rs2 = stmt2.executeQuery();
                int totalEarnedMoney = 0;
                if (rs2.next()) {
                    totalEarnedMoney = rs2.getInt(1);
                }
                stmt2.close();
                
                tblmodel.addRow(new Object[]{artistId, artistName, artistAge, artistNationality, totalArtwork, totalBoughtPhotos, totalEarnedMoney});
            }
            
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
 
    
    private void set_customer_tbl() {
        try {
        DefaultTableModel tblmodel = (DefaultTableModel) customertbl.getModel();
        tblmodel.setRowCount(0); // Clear existing rows
        
        PreparedStatement stmt = connection.prepareStatement("SELECT * FROM customer");
        ResultSet rs = stmt.executeQuery();
        
        while (rs.next()) {
            int customerId = rs.getInt("custid"); // Assuming custid is the correct column name for customer id
            String customerName = rs.getString("name"); // Corrected column name
            String customerAddress = rs.getString("address"); // Corrected column name
            
            PreparedStatement stmt2 = connection.prepareStatement("SELECT COUNT(*) FROM buys_artwork WHERE custid = ?");
            stmt2.setInt(1, customerId);
            ResultSet rs2 = stmt2.executeQuery();
            int totalBoughtPhotos = 0;
            if (rs2.next()) {
                totalBoughtPhotos = rs2.getInt(1);
            }
            stmt2.close();
            
            tblmodel.addRow(new Object[]{customerId, customerName, customerAddress, totalBoughtPhotos});
        }
        
        stmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private javax.swing.JTabbedPane adminbody;
    private javax.swing.JTable artisttbl;
    private javax.swing.JLabel closeicon;
    private javax.swing.JTable customertbl;
    private javax.swing.JPanel datatblstab;
    private javax.swing.JPanel hometab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minminze;
    private javax.swing.JLabel totalartboughtphtotolabel3;
    private javax.swing.JLabel totalartboughtphtotolabel4;
    private javax.swing.JLabel totalartsitslabel;
    private javax.swing.JLabel totalartsitslabel1;
    private javax.swing.JLabel totalartworkslabel2;
    private javax.swing.JLabel totalartworkslabel3;
    private javax.swing.JLabel totalcustomersslabel1;
    private javax.swing.JLabel totalcustomersslabel2;
    private javax.swing.JLabel totalearnedmoneylabel4;
    private javax.swing.JLabel totalearnedmoneylabel5;
    // End of variables declaration//GEN-END:variables
}
