/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import ALLCLASS.*;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class CustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPage
     */
    public String userid;
//    private String addimagepath;
//    private ARTWORK customerartwork[];
//    private int customerartworksize = 0;
//    private ARTWORK avaliableartwork[];
//    private int avaliableartworksize = 0;
//    
//    private int changephotoinportfolio;
//    private int changephotoinbuyphoto;
//    private Boolean ava_search ;       
//    private int totalearnedmoney = 0 ;

    
    
    public CustomerPage(String userid) {
        initComponents();
        this.setLocationRelativeTo(null);
        
//        customerartwork = new ARTWORK[50];
//        avaliableartwork = new ARTWORK[50];
        
     
        
        
//        avaliableartwork = get_avaliable_img();
//       setbuyphotodata();
       //set_portfolio_data();
       this.userid = userid;
       setprofiledata(this.userid);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        minminze = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        yourprofiletab1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        setidlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        setnamelabel1 = new javax.swing.JLabel();
        totalearnedmoneylabel = new javax.swing.JLabel();
        galleryvisit = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Head.setBackground(new java.awt.Color(0, 0, 0));

        minminze.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minminze.setForeground(new java.awt.Color(255, 255, 255));
        minminze.setText("-");
        minminze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minminze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minminzeMouseClicked(evt);
            }
        });

        closeicon.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        closeicon.setForeground(new java.awt.Color(255, 255, 255));
        closeicon.setText("X");
        closeicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ART GALLERY");

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(426, 426, 426)
                .addComponent(minminze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeicon)
                .addGap(12, 12, 12))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeicon)
                    .addComponent(minminze)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        yourprofiletab1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        idlabel.setBackground(new java.awt.Color(204, 255, 51));
        idlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idlabel.setText("ID :");

        setidlabel.setBackground(new java.awt.Color(204, 255, 51));
        setidlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setidlabel.setText(" ");

        namelabel.setBackground(new java.awt.Color(204, 255, 51));
        namelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelabel.setText("Name :");

        setnamelabel1.setBackground(new java.awt.Color(204, 255, 51));
        setnamelabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnamelabel1.setText(" ");

        totalearnedmoneylabel.setBackground(new java.awt.Color(204, 255, 51));
        totalearnedmoneylabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalearnedmoneylabel.setText("Gallery Visting : ");

        galleryvisit.setBackground(new java.awt.Color(204, 255, 51));
        galleryvisit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        galleryvisit.setText(" ");

        address.setBackground(new java.awt.Color(204, 255, 51));
        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setText("Address of Customer");

        add.setBackground(new java.awt.Color(204, 255, 51));
        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setText(" ");

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Personal Information");

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("CLICK ON THE PHOTO TO BOOK ARTWORK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(totalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(galleryvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelabel)
                            .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(address)
                        .addGap(18, 18, 18)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(galleryvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        yourprofiletab1.add(jPanel1);
        jPanel1.setBounds(40, 260, 430, 350);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/quan-jing-O2VatZ9gHmk-unsplash.jpg"))); // NOI18N
        jButton2.setText("BOOK ARTWORK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        yourprofiletab1.add(jButton2);
        jButton2.setBounds(500, 310, 390, 300);

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cristine-enero-GFchtr4m4OQ-unsplash.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        yourprofiletab1.add(jLabel16);
        jLabel16.setBounds(-10, -300, 1460, 1150);

        jLabel2.setText("jLabel2");
        yourprofiletab1.add(jLabel2);
        jLabel2.setBounds(660, 300, 220, 110);

        jButton3.setText("jButton3");
        yourprofiletab1.add(jButton3);
        jButton3.setBounds(520, 260, 75, 23);

        jLabel4.setText("jLabel4");
        yourprofiletab1.add(jLabel4);
        jLabel4.setBounds(570, 270, 38, 16);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        yourprofiletab1.add(jPanel2);
        jPanel2.setBounds(510, 260, 290, 40);

        jTabbedPane1.addTab("Your Profile", yourprofiletab1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private ImageIcon resizeImage(String imagepath , byte[] pic,JLabel x)
//    {
//        ImageIcon myimg = null;
//        if(imagepath !=null)
//            myimg = new ImageIcon(imagepath);
//        else
//            myimg = new ImageIcon(pic);
//        Image img = myimg.getImage();
//        Image img2 = img.getScaledInstance(x.getWidth(),x.getHeight(),Image.SCALE_SMOOTH);
//        
//        ImageIcon imageicon = new ImageIcon(img2);
//        
//    return imageicon;
//    }
    
//    private ARTWORK[] get_avaliable_img()
//    {
//          ARTWORK avawork[] = new ARTWORK[50];
//           avaliableartworksize = 0;   
//        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
//        {
//            if(ReadWriteDataFromFiles.artwork[i].getIdCustomer()== 0)
//            {
//                avawork[avaliableartworksize] = ReadWriteDataFromFiles.artwork[i];
//                avaliableartworksize++;
//            }
//        }
//        return avawork;
//    }
//    private ARTWORK[] get_avalible_search_img(String category_search)
//    {
//           ARTWORK avawork[] = new ARTWORK[50];
//           int c = 0;   
//           ava_search = false;
//        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
//        {
//            if(category_search.equals(ReadWriteDataFromFiles.artwork[i].getTypeOfArt()) && ReadWriteDataFromFiles.artwork[i].getIdCustomer()== 0)
//            {
//                avawork[c] = ReadWriteDataFromFiles.artwork[i];
//                ava_search = true;
//                c++;
//            }
//        }
//        if(c > 0)
//            avaliableartworksize = c;
//        return avawork;
//    }
    
//    private void get_customer_img()
//    {
//        customerartworksize = 0;
//        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
//        {
//            if(ReadWriteDataFromFiles.artwork[i].getIdCustomer() == LOGINFORM.SignInid )
//            {
//                customerartwork[customerartworksize] = ReadWriteDataFromFiles.artwork[i];
//                customerartworksize++;
//            }
//        }
//    }
    
//    private void set_portfolio_data()
//    {
//        if(customerartworksize > 0)
//        {
//         photoplacejLabel2.setIcon(resizeImage(customerartwork[changephotoinportfolio].getPath(), null,photoplacejLabel2));
//         setidLabel9.setText("" + customerartwork[changephotoinportfolio].getId());
//         settitleLabel11.setText(customerartwork[changephotoinportfolio].getTitle());
//         setpriceLabel10.setText("" +customerartwork[changephotoinportfolio].getPrice()); 
//         seyearLabel12.setText("" +customerartwork[changephotoinportfolio].getYear()); 
//         setcategoryLabel13.setText(customerartwork[changephotoinportfolio].getTypeOfArt());
//         try
//         {
//             setartistmaderLabel14.setText(ReadWriteDataFromFiles.pearsons[customerartwork[changephotoinportfolio].getIdArtist()-1].getName()); 
//         }
//         catch(Exception e)
//         {
//             setartistmaderLabel14.setText("Admin");
//         }
//         chngenuberlabel.setText((changephotoinportfolio +1)+ "/" + customerartworksize);
//        }
//        else
//        {
//         photoplacejLabel2.setIcon(null);
//         setidLabel9.setText("");
//         settitleLabel11.setText("");
//         setpriceLabel10.setText(""); 
//         seyearLabel12.setText(""); 
//         setcategoryLabel13.setText("");
//         setartistmaderLabel14.setText(""); 
//         chngenuberlabel.setText("");
//        }
//    }
    
//    private void setprofiledata()
//    {
//        int getid = LOGINFORM.SignInid;
//if (getid >= 1) { // Ensure SignInid is valid
//    getid--; // Adjust index to start from 0
//    CUSTOMER customer = new CUSTOMER();
//    customer = (CUSTOMER) ReadWriteDataFromFiles.pearsons[getid].get_data();
//
//    setidlabel.setText("" + customer.getId());
//    setnamelabel1.setText(customer.getName());
//    setaddresslabel.setText(customer.getAddress());
//         
//    int totalearnedmoney = 0;
//    for (int i = 0; i < customerartworksize; i++) {
//        totalearnedmoney += customerartwork[i].getPrice();
//    }
//    settotalearnedmoneylabel.setText("" + totalearnedmoney + " $");
//    setnofboughtphotolabel1.setText("" + customerartworksize);
//} else {
//    // Handle case when SignInid is not valid
//    // For example, display an error message or take appropriate action
//}
       
//  }
    
    
public void setprofiledata(String userId) {
    if (!userId.isEmpty()) { // Check if user ID is not empty
        int userIdIntU = Integer.parseInt(userId); // Convert user ID from String to int
        if (userIdIntU >= 0) { // Ensuring userId is valid
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/art_management", "root", "manya123");  
                String queryA = "SELECT custid FROM customer WHERE password=(SELECT password FROM users WHERE userid=?)";
                PreparedStatement pstmta = con.prepareStatement(queryA);
                pstmta.setInt(1, userIdIntU);
                ResultSet rsa = pstmta.executeQuery();
                // Retrieve customer data using userId
                if(rsa.next()){
                int custid = rsa.getInt("custid");
                String query = "SELECT * FROM customer WHERE custid = ?";
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setInt(1, custid);
                ResultSet rs = pstmt.executeQuery();
                
                if (rs.next()) {
                    // Retrieving customer details from the database
                    String name = rs.getString("name");
                    String address = rs.getString("address");
                    String gid = rs.getString("gid");

                    // Displaying customer details on the UI
                    setidlabel.setText(String.valueOf(custid));
                    setnamelabel1.setText(name);
//                    setaddresslabel.setText(address);
                    galleryvisit.setText(gid);
                    add.setText(address);
                    // Additional operations if needed
                    
                } }else {
                    JOptionPane.showMessageDialog(this, "No customer found with the given user ID.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Handle case when userId is not valid
            // For example, display an error message or take appropriate action
        }
    } else {
        // Handle case when user ID is empty
        // For example, display an error message or take appropriate action
    }
}

    
    

    
    
    private void minminzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minminzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minminzeMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        //System.exit(0);
        this.dispose();
        new LOGINFORM().setVisible(true);
    }//GEN-LAST:event_closeiconMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new DisplayArtwork().setVisible(true);
        }
        });
    }//GEN-LAST:event_jButton2MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private javax.swing.JLabel add;
    private javax.swing.JLabel address;
    private javax.swing.JLabel closeicon;
    private javax.swing.JLabel galleryvisit;
    private javax.swing.JLabel idlabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel minminze;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel setidlabel;
    private javax.swing.JLabel setnamelabel1;
    private javax.swing.JLabel totalearnedmoneylabel;
    private javax.swing.JPanel yourprofiletab1;
    // End of variables declaration//GEN-END:variables
}
